import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import AxeBuilder from '@axe-core/playwright';
const root=fileURLToPath(new URL('../',import.meta.url));
const uid='qa-xverse-'+Date.now();
fs.writeFileSync(root+'qa-user.txt',uid);
const token='test.'+Buffer.from(JSON.stringify({sub:uid,display_name:'QA Learner'})).toString('base64url')+'.test';
const b=await chromium.launch({channel:'chrome'});
try {
const ctx=await b.newContext({viewport:{width:1440,height:1040},deviceScaleFactor:2,reducedMotion:'reduce',extraHTTPHeaders:{'X-PromptQL-Visitor-Token':token}});
const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:8000/',{waitUntil:'networkidle'});
assert.equal(await p.getByRole('button',{name:'X Verse home'}).count(),1);
assert.equal(await p.locator('.fox-launcher').count(),0);
assert.equal(await p.locator('.track-card').count(),4);
assert(!/CokeBoys|Nori|companion|coming soon|JavaScript · later/i.test(await p.locator('body').innerText()));
await p.screenshot({path:root+'xverse-desktop.png'});
await p.getByRole('button',{name:'Customize appearance'}).click();
assert.equal(await p.getByRole('switch',{name:'Nori fox companion'}).count(),0);
await p.getByRole('button',{name:'Nebula Muted violet'}).click();
await p.getByRole('button',{name:'Close dialog'}).click();
assert.equal(await p.locator('html').getAttribute('data-theme'),'nebula');
await p.getByRole('button',{name:'JavaScript 30 lessons · available now',exact:true}).click();
assert.equal(await p.locator('.lesson-row').count(),30);
await p.getByRole('button',{name:/Run your first JavaScript program Use the console/}).click();
await p.getByRole('button',{name:'Load example solution'}).click();
await p.getByRole('button',{name:'Run code checks'}).click();
await p.locator('.check-results .passed').first().waitFor();
assert.equal(await p.locator('.check-results .passed').count(),2);
assert((await p.getByRole('log',{name:'Program output'}).innerText()).includes('Hello, X Verse!'));
await p.getByRole('button',{name:/B A JavaScript runtime outside/}).click();
await p.getByRole('button',{name:'Check answer',exact:true}).click();
await p.getByRole('button',{name:/Complete lesson/}).click();
await p.getByRole('button',{name:'Next lesson',exact:true}).waitFor();
console.log('PASS JS exercise, runtime, quiz and completion');
await p.getByRole('button',{name:'Java 30 lessons · available now',exact:true}).click();
assert.equal(await p.locator('.lesson-row').count(),30);
await p.getByRole('button',{name:/Your first Java program Compile and run/}).click();
await p.getByRole('button',{name:'Load example solution'}).click();
await p.getByRole('button',{name:'Run Java',exact:true}).click();
await p.getByRole('log',{name:'Program output'}).getByText('Hello, Java!',{exact:true}).waitFor();
await p.screenshot({path:root+'xverse-java.png'});
console.log('PASS Java compile and run');
await p.getByRole('button',{name:'Code lab LIVE',exact:true}).click();
await p.getByRole('button',{name:'JavaScript',exact:true}).click();
const source='console.log("Saved JS draft");';
await p.getByRole('textbox',{name:'JavaScript code'}).fill(source);
await p.getByRole('button',{name:'Java',exact:true}).click();
await p.getByRole('button',{name:'JavaScript',exact:true}).click();
assert.equal(await p.getByRole('textbox',{name:'JavaScript code'}).inputValue(),source);
await p.waitForTimeout(1700);
await p.reload({waitUntil:'networkidle'});
await p.getByRole('button',{name:'Code lab LIVE',exact:true}).click();
await p.getByRole('button',{name:'JavaScript',exact:true}).click();
assert.equal(await p.getByRole('textbox',{name:'JavaScript code'}).inputValue(),source);
await p.getByRole('textbox',{name:'JavaScript code'}).fill('throw new Error("Example failure");');
await p.getByRole('button',{name:'Run JavaScript',exact:true}).click();
await p.locator('.error-output').waitFor();
assert((await p.locator('.error-output').innerText()).includes('Example failure'));
console.log('PASS draft isolation, navigation flush, reload and error output');
const overflows=[];
for(const [nav,label] of [['X Verse home','overview'],['Learning paths 106','courses'],['Code lab LIVE','lab'],['Project studio','projects'],['Field guide','reference'],['Your progress','progress']]){
 await p.setViewportSize({width:1440,height:1040});await p.getByRole('button',{name:nav,exact:true}).click();
 for(const width of [780,560,390,320]){
  await p.setViewportSize({width,height:900});await p.waitForTimeout(100);
  const overflow=await p.locator('#content').evaluate(e=>e.scrollWidth>e.clientWidth+1);
  overflows.push({label,width,overflow});
 }
}
assert(!overflows.some(x=>x.overflow),JSON.stringify(overflows));
await p.setViewportSize({width:1440,height:1040});
await p.getByRole('button',{name:'X Verse home'}).click();
await p.getByRole('button',{name:'Customize appearance'}).click();
await p.getByRole('button',{name:'Hologram Cool blue'}).click();
await p.getByRole('button',{name:'Close dialog'}).click();
const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
console.log('Accessibility',JSON.stringify(a.violations.map(v=>({id:v.id,nodes:v.nodes.slice(0,2).map(n=>({html:n.html,why:n.failureSummary}))}))));
await p.setViewportSize({width:390,height:844});
await p.screenshot({path:root+'xverse-mobile.png'});
console.log('PASS responsive layouts',JSON.stringify(overflows));
assert.deepEqual(errors,[]);console.log('PASS zero JS errors; 4 courses and no companion');
} finally {await b.close()}