import { chromium } from 'playwright';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
const out=fileURLToPath(new URL('../',import.meta.url));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--force-device-scale-factor=2']});
const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:2});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8000/',{waitUntil:'networkidle'});
await page.getByRole('heading',{name:'Pick up where you left off.'}).waitFor();
await page.screenshot({path:out+'desktop.png'});
const results=[];
for(const [w,h] of [[1440,1040],[1024,768],[768,1000],[560,850],[390,844],[320,740]]){
 await page.setViewportSize({width:w,height:h});
 await page.waitForTimeout(200);
 results.push({width:w,bodyOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),mainOverflow:await page.locator('main#content').evaluate(e=>e.scrollWidth>e.clientWidth)});
}
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:out+'mobile.png'});
await page.getByRole('button',{name:'Start learning'}).click();
await page.getByRole('heading',{name:'Your first document.'}).waitFor();
await page.getByRole('button',{name:'Load example solution'}).click();
await page.getByRole('button',{name:'Run code checks'}).click();
await page.locator('.check-results').waitFor();
results.push({codeChecks:await page.locator('.check-results').innerText()});
await page.getByRole('button',{name:'B <body>'}).click();
await page.getByRole('button',{name:'Check answer',exact:true}).click();
results.push({quiz:await page.locator('.quiz-explanation').innerText()});
await page.getByRole('button',{name:'Complete lesson'}).click();
await page.waitForTimeout(300);
results.push({anonymousCompletionToast:await page.locator('.toast').innerText()});
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('button',{name:'Code lab LIVE'}).click();
await page.getByRole('heading',{name:'Write, run, and test.'}).waitFor();
await page.getByRole('tab',{name:'styles.css'}).click();
await page.getByRole('textbox',{name:'CSS code'}).fill('body { background: #ff00aa; color: white; }');
await page.waitForTimeout(450);
results.push({previewBodyBackground:await page.frameLocator('iframe').locator('body').evaluate(el=>getComputedStyle(el).backgroundColor)});
await page.getByRole('textbox',{name:'CSS code'}).press('Escape');
await page.getByRole('textbox',{name:'CSS code'}).press('Tab');
results.push({editorEscape:await page.evaluate(()=>document.activeElement.tagName!=='TEXTAREA')});
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('button',{name:'Project studio',exact:true}).click();
await page.getByRole('button',{name:/Your personal orbit/}).click();
await page.getByRole('heading',{name:'Your personal orbit.'}).waitFor();
results.push({projectEditor:await page.getByRole('textbox',{name:'HTML code'}).count()});
await page.setViewportSize({width:1440,height:1040});
await page.getByRole('button',{name:'Field guide',exact:true}).click();
await page.getByRole('textbox',{name:'Search field guide'}).fill('container');
results.push({referenceFiltered:await page.locator('.reference-card').count()});
await page.getByRole('button',{name:'Search anything'}).click();
await page.getByRole('textbox',{name:'Search all lessons'}).fill('animation');
results.push({searchResults:await page.locator('.search-results>button').count()});
await page.getByRole('button',{name:'Keyframes & cinematic motion'}).click();
await page.getByRole('heading',{name:'Keyframes & cinematic motion.'}).waitFor();
await page.screenshot({path:out+'lesson.png'});
results.push({pageErrors:errors});
console.log(JSON.stringify(results,null,2));
await browser.close();