import assert from 'node:assert/strict';
import {pairedTagEdit,completeTypedTag} from './src/editor-tools.js';
let count=0;
function pair(input,expected,caret=input.length){const out=pairedTagEdit(input,caret);assert.equal(out?.value??input,expected,input);if(out)assert.equal(out.caret,caret);count++}
pair('<title>','<title></title>');
pair('<DIV>','<DIV></DIV>');
pair('<section class="a">','<section class="a"></section>');
pair('<a title="1 > 0">','<a title="1 > 0"></a>');
pair("<a title='hello > you'>","<a title='hello > you'></a>");
pair('<my-card>','<my-card></my-card>');
pair('<div><p>','<div><p></p>');
pair('<button>later','<button></button>later',8);
pair('<title></title>','<title></title>',7);
pair('<TITLE>\n  </title>','<TITLE>\n  </title>',7);
pair('<div/>','<div/>');
pair('<my-card />','<my-card />');
pair('</title>','</title>');
pair('<!doctype html>','<!doctype html>');
pair('<!-- <div>','<!-- <div>');
pair('<!-- <div> -->','<!-- <div> -->');
pair('<!-- <div> -->\n<p>','<!-- <div> -->\n<p></p>');
pair('<![CDATA[<div>','<![CDATA[<div>');
pair('<a title="1 >','<a title="1 >');
pair('<textarea><div>','<textarea><div>');
pair('<title><b>','<title><b>');
pair('<style>p::before {content:"<div>','<style>p::before {content:"<div>');
pair('<script>const a="<div>','<script>const a="<div>');
pair('<script>const a="<div>";</script><div>','<script>const a="<div>";</script><div></div>');
pair('2 > 1','2 > 1');
pair('<notanelement>','<notanelement>');
for(const name of 'area base br col embed hr img input link meta param source track wbr'.split(' '))pair(`<${name}>`,`<${name}>`);
assert.equal(completeTypedTag('<div','<div>',5,'insertFromPaste'),null);
assert.equal(completeTypedTag('<div','<div>',5,'insertText',false),null);
assert.equal(completeTypedTag('<div>','<div>',5,'insertText'),null);
assert.equal(completeTypedTag('<div','<div>',5,'insertText').value,'<div></div>');
assert.equal(completeTypedTag('','<div>',5,'insertText'),null);
console.log(`PASS: ${count+5} smart tag edge cases`);