import json
from pathlib import Path

LESSONS=[]
def lesson(track, module, slug, title, minutes, summary, learn, html, css, task, checks, question, options, answer, explanation, solution_html=None, solution_css=None, reference=None):
    LESSONS.append(dict(id=slug,track=track,module=module,title=title,minutes=minutes,summary=summary,learn=learn,html=html,css=css,task=task,checks=checks,quiz=dict(question=question,options=options,answer=answer,explanation=explanation),solution_html=solution_html or html,solution_css=solution_css or css,reference=reference or ('https://developer.mozilla.org/en-US/docs/Web/HTML' if track=='html' else 'https://developer.mozilla.org/en-US/docs/Web/CSS')))
BASE="body { font-family: system-ui, sans-serif; padding: 32px; background: #f6f7fb; color: #182033; line-height: 1.6; }\nh1 { line-height: 1.1; }\n"
def H(module,slug,title,minutes,summary,learn,html,task,checks,q,opts,ans,exp,solution,css=BASE):
    lesson('html',module,slug,title,minutes,summary,learn,html,css,task,checks,q,opts,ans,exp,solution)
def C(module,slug,title,minutes,summary,learn,html,css,task,checks,q,opts,ans,exp,solution):
    lesson('css',module,slug,title,minutes,summary,learn,html,css,task,checks,q,opts,ans,exp,solution_css=solution)

H("01 / Foundations","html-document","Your first document",8,"Turn a blank file into a real web page.",[
("The browser is an interpreter","HTML describes the structure and meaning of a document. A browser parses it into a tree called the DOM. CSS changes how that tree looks; JavaScript can change how it behaves."),
("Start with a document skeleton","Use <!doctype html> to select standards mode. The html element wraps the document. Put metadata in head and visible content in body. Set lang=\"en\" so assistive technologies know the language."),
("Give every page an identity","A title names the browser tab, not the visible page heading. charset=\"UTF-8\" supports international text. The viewport meta tag makes mobile browsers use the device width. Keep one clear main heading for this exercise.")
],'<main>\n  <!-- Add a heading and a paragraph here. -->\n</main>',"Inside main, add an h1 with your academy name and a p explaining what you will build.",[["tag","h1"],["tag","p"]],"Where does the visible page content belong?",["<head>","<body>","<title>"],1,"The body contains visible document content; the head holds metadata.","<main>\n  <h1>Hello, future developer.</h1>\n  <p>I am learning to build the web.</p>\n</main>")

H("01 / Foundations","html-elements","Elements & attributes",9,"Understand the building blocks of every interface.",[
("Anatomy of an element","Most elements have an opening tag, content, and a closing tag: <p>Hello</p>. Void elements such as img and input have no closing tag. Nest elements without crossing their boundaries."),
("Attributes configure elements","Attributes live in the opening tag. In <a href=\"/about\">About</a>, href is the attribute name. Quote values. Boolean attributes such as disabled are true by their presence: disabled=\"false\" still disables a button."),
("Classes are reusable labels","Use class to group elements for styling. An id must be unique within a document and can be the target of a fragment link. Class and id do not add semantics by themselves.")
],'<section>\n  <h1>Mission control</h1>\n  <button>Launch</button>\n</section>',"Give the button class=\"launch\" and add the disabled attribute.",[["attr","button","class","launch"],["attr","button","disabled"]],"What does disabled=\"false\" do on a button?",["Enables it","Disables it","Changes its label"],1,"Boolean attributes are true when present, regardless of their string value.",'<section><h1>Mission control</h1><button class="launch" disabled>Launch</button></section>')

H("01 / Foundations","html-text","Headings & meaningful text",9,"Give your content a readable hierarchy.",[
("Headings outline the page","h1 through h6 express hierarchical sections, not font sizes. Nest heading levels logically; use CSS to change their appearance. Screen reader users often jump between headings."),
("Emphasis has meaning","Use strong for importance and em for stress emphasis. Use p for paragraphs, not repeated br elements. br is appropriate for meaningful line breaks such as an address or poem."),
("Represent code correctly","code marks a code fragment and pre preserves whitespace. Escape < as &lt; and & as &amp; when showing source as text. Use blockquote for extended quoted content, not indentation.")
],'<article>\n  <h1>Developer journal</h1>\n</article>',"Add an h2, a paragraph containing strong, and an inline code element.",[["tag","h2"],["tag","p"],["tag","strong"],["tag","code"]],"Should you pick h4 just because its default size looks good?",["Yes, headings are only visual","No, use logical headings and style with CSS","Only on mobile"],1,"Heading levels describe structure. CSS controls size.",'<article><h1>Developer journal</h1><h2>Day one</h2><p><strong>Structure matters.</strong> Start with <code>&lt;main&gt;</code>.</p></article>')

H("01 / Foundations","html-links","Links & navigation",10,"Connect pages, sections, and destinations.",[
("Links navigate; buttons act","An a element with href navigates to a URL. Use a button for an action such as opening a dialog. Text like “Read the accessibility guide” is more useful than “Click here”."),
("Relative and absolute URLs","https://example.com/ is absolute. /about is relative to the site root; ./about is relative to the current document. #contact navigates to an element with id=\"contact\"."),
("New tabs need care","Open a new tab only when useful and tell users. target=\"_blank\" opens a new browsing context. Use rel=\"noopener\" explicitly; add noreferrer only if you also want to suppress the Referer header.")
],'<nav aria-label="Main navigation">\n</nav>\n<section id="contact"><h1>Get in touch</h1></section>',"Add a link inside nav that navigates to #contact.",[["attr","a","href","#contact"]],"Which element is best for navigating to another page?",["<button>","<a href=\"…\">","<div onclick=\"…\">"],1,"Anchors with href provide native navigation, keyboard support, and browser link behavior.",'<nav aria-label="Main navigation"><a href="#contact">Contact us</a></nav><section id="contact"><h1>Get in touch</h1></section>')

H("02 / Content","html-lists","Lists & grouped content",8,"Organize steps, collections, and definitions.",[
("Choose the right list","Use ul when order is not meaningful and ol when sequence or rank matters. Each list item is an li. Lists communicate relationships to assistive technology."),
("Nest within a list item","A nested list belongs inside an li, not directly beside it. CSS can remove bullets without changing the underlying content structure."),
("Name/value groups","dl contains terms in dt and descriptions in dd. It suits glossaries or metadata; it is not a generic two-column layout tool.")
],'<h1>Your launch sequence</h1>',"Add an ordered list with at least three list items.",[["tag","ol"],["count","li",3]],"Which element describes steps whose order matters?",["<ul>","<ol>","<dl>"],1,"An ordered list conveys meaningful sequence.",'<h1>Your launch sequence</h1><ol><li>Plan the structure</li><li>Write the HTML</li><li>Style the page</li></ol>')

H("02 / Content","html-images","Images & alternative text",10,"Use images without leaving anyone behind.",[
("Two essential attributes","img uses src for the resource and alt for a text alternative. Describe the image’s purpose in context, not every visual detail. For decorative images, use alt=\"\" so screen readers skip them."),
("Prevent layout shifts","Set width and height to establish an aspect ratio before the image loads. CSS can make the actual width responsive. Lazy-load below-the-fold images, not the important hero image."),
("Caption a figure","figure groups self-contained media. figcaption provides a visible caption. A visible caption and alt text serve related but different purposes.")
],'<figure>\n  <img src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600" width="600" height="400">\n</figure>',"Give the image meaningful alt text and add a figcaption.",[["attr_nonempty","img","alt"],["tag","figcaption"]],"What is appropriate alt text for a purely decorative image?",['alt=""','alt="Image"',"Omit alt entirely"],0,"An empty alt explicitly marks an image as decorative.",'<figure><img src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600" alt="Sunlight filtering through a green forest" width="600" height="400"><figcaption>Find inspiration in nature.</figcaption></figure>',BASE+'img { max-width: 100%; height: auto; }')

H("02 / Content","html-semantics","Semantic page architecture",12,"Build landmarks, not a soup of divs.",[
("Landmarks make pages navigable","Use header for introductory content, nav for major navigation, main for the dominant content, and footer for related closing information. Typically only one non-hidden main is present."),
("Section versus article","article is self-contained content that could stand on its own. section groups a thematic part of a document, usually with a heading. A div is appropriate when only a styling wrapper is needed."),
("Semantics are not appearance","An aside is tangential content; it does not mean “anything on the right”. Native semantics survive CSS changes and help search engines and assistive technologies understand a page.")
],'<h1>Signal magazine</h1>\n<p>Stories from the web.</p>',"Create header, main with an article, and footer landmarks.",[["tag","header"],["tag","main"],["tag","article"],["tag","footer"]],"Which element represents self-contained content?",["<article>","<div>","<span>"],0,"An article is an independently reusable unit, such as a story or post.",'<header><h1>Signal magazine</h1></header><main><article><h2>A better web</h2><p>Make structure meaningful.</p></article></main><footer>Made with care.</footer>')

H("02 / Content","html-tables","Accessible data tables",12,"Present relationships without using tables for layout.",[
("Rows and cells","table contains rows (tr), data cells (td), and header cells (th). Use a table only for genuinely tabular data, not for arranging a page."),
("Associate headers","Use scope=\"col\" or scope=\"row\" on simple header cells. Complex tables can use id and headers associations, but simpler tables are often easier to understand."),
("Supply context","A caption describes what the table shows. thead and tbody group rows. On small screens, an overflow container can preserve the table structure without shrinking text.")
],'<table>\n  <tr><td>HTML</td><td>Structure</td></tr>\n</table>',"Add a caption and a header row with two th elements using scope=\"col\".",[["tag","caption"],["count","th",2],["attr","th","scope","col"]],"What is a table caption for?",["Styling its border","Describing the table's subject","Creating a new column"],1,"The caption gives the data table an accessible title.",'<table><caption>Web languages</caption><thead><tr><th scope="col">Language</th><th scope="col">Purpose</th></tr></thead><tbody><tr><td>HTML</td><td>Structure</td></tr></tbody></table>',BASE+'td, th { padding: 12px; border: 1px solid #cbd5e1; } table { border-collapse: collapse; }')

H("03 / Forms","html-forms","Forms & labels",12,"Collect input with native, accessible controls.",[
("Forms connect controls to submission","form groups fields for a submission. action defines the destination and method defines the HTTP method. GET places values in the URL; POST sends them in the request body. Neither replaces HTTPS."),
("Every control needs a name","The name attribute is the key sent to the server. An id alone is not submitted. Associate label for=\"email\" with input id=\"email\"; a placeholder is not a substitute for a visible label."),
("Use explicit button types","Inside forms, a button defaults to submit. Set type=\"button\" for non-submission actions. This practice lab is a sandbox: forms demonstrate markup but do not send data.")
],'<form>\n  <input id="email" type="email" name="email">\n</form>',"Add a label linked to email and a button with type=\"submit\".",[["attr","label","for","email"],["attr","button","type","submit"]],"Which input attribute becomes the submitted field key?",["id","class","name"],2,"name is used in the form's submitted name/value pair.",'<form><label for="email">Email address</label><input id="email" name="email" type="email"><button type="submit">Join the mission</button></form>')

H("03 / Forms","html-inputs","Input types & validation",12,"Let the browser do the useful work.",[
("Choose appropriate types","email, url, number, date, checkbox, and radio provide native behavior. Use inputmode to hint at a keyboard when type alone is not right. Telephone numbers are text-like identifiers, not arithmetic numbers."),
("Declare constraints","required prevents empty submission; minlength and maxlength constrain text; min, max, and step constrain numeric/date-like fields. type=\"email\" checks syntax, not whether an address exists."),
("Validation is not security","Client validation improves feedback and can be bypassed. Servers must validate every received value too. Describe expected formats before users encounter errors, and associate help text using aria-describedby.")
],'<form><label for="age">Age</label><input id="age" name="age" type="number"><button>Continue</button></form>',"Make the age input required with min=\"13\" and max=\"120\".",[["attr","input","required"],["attr","input","min","13"],["attr","input","max","120"]],"Is browser validation sufficient to protect a server?",["Yes","No, the server must validate too","Only for email fields"],1,"A caller can bypass the page and send requests directly.",'<form><label for="age">Age</label><input id="age" name="age" type="number" min="13" max="120" required><button>Continue</button></form>')

H("03 / Forms","html-choice","Selections & grouped controls",10,"Design clear choices.",[
("Radio versus checkbox","Radio inputs with the same name form a single-choice group. Checkboxes allow independent choices. Give each choice a distinct value so the server knows what was selected."),
("Group related fields","fieldset groups related controls; legend names the group. Each individual control still needs its own label. Do not rely on position or color to explain the choices."),
("Select and textarea","select with option provides a native choice list. textarea is for multiline text; its initial value is text between its tags, not a value attribute.")
],'<form>\n</form>',"Build a fieldset with a legend and two radio inputs sharing name=\"level\". Label both choices.",[["tag","fieldset"],["tag","legend"],["count","label",2],["count","input",2],["attr","input","type","radio"],["attr","input","name","level"]],"How do you group radio inputs into a single choice?",["Give them the same name","Give them the same id","Put them on the same line"],0,"The shared name defines the radio group.",'<form><fieldset><legend>Your experience</legend><label><input type="radio" name="level" value="beginner"> Beginner</label><label><input type="radio" name="level" value="advanced"> Advanced</label></fieldset></form>')

H("04 / Beyond basics","html-media","Audio, video & captions",12,"Embed media responsibly.",[
("Native media elements","audio and video provide built-in playback with controls. Include fallback text. source lets you offer alternative encodings; the browser picks one it can play."),
("Accessibility is part of media","Provide captions for speech and important sounds using track with kind=\"captions\" and a WebVTT file. Offer a transcript, and audio description when important visual information is not spoken."),
("Performance and consent","Avoid autoplay with sound. Use preload=\"metadata\" or \"none\" to limit early downloads. A poster gives video a useful initial frame. This example focuses on markup; replace the placeholder media URLs with real files.")
],'<video controls width="320">\n  <source src="lesson.mp4" type="video/mp4">\n</video>',"Add a captions track with src, srclang=\"en\", and label=\"English\".",[["attr","track","kind","captions"],["attr","track","srclang","en"],["attr_nonempty","track","src"]],"Which format is commonly used for HTML video captions?",["WebVTT","JPEG","CSV"],0,"The track element commonly references a WebVTT (.vtt) file.",'<video controls width="320" preload="metadata"><source src="lesson.mp4" type="video/mp4"><track kind="captions" src="captions.vtt" srclang="en" label="English"><p>Read the transcript instead.</p></video>')

H("04 / Beyond basics","html-responsive-images","Responsive images",12,"Send the right image for the device.",[
("Resolution and width candidates","srcset lists candidate resources. Width descriptors such as 480w pair with sizes, which describes the expected rendered width. Density descriptors such as 2x fit fixed-size images."),
("The browser chooses","sizes=\"(max-width: 600px) 100vw, 50vw\" predicts the image’s layout width; it does not style the image. The browser considers pixel density and available candidates."),
("Art direction with picture","picture supplies different compositions or formats through source elements with media/type. Keep an img fallback inside picture; its alt provides the text alternative.")
],'<img src="small.jpg" alt="A mountain landscape" width="800" height="500">',"Add srcset with 480w and 960w candidates, and a sizes attribute.",[["attr_nonempty","img","srcset"],["attr_nonempty","img","sizes"]],"Does the sizes attribute set the CSS width of an image?",["Yes","No, it informs resource selection","Only on phones"],1,"CSS controls layout. sizes helps select an appropriate srcset resource.",'<img src="small.jpg" srcset="small.jpg 480w, large.jpg 960w" sizes="(max-width: 600px) 100vw, 50vw" alt="A mountain landscape" width="800" height="500">')

H("04 / Beyond basics","html-metadata","Metadata & discoverability",10,"Make the document understandable outside its viewport.",[
("Useful head metadata","A concise, unique title identifies the page. A meta description summarizes it and may inform a search result snippet, but search engines may use different text."),
("Canonical URLs and sharing","A canonical link suggests a preferred URL for duplicate content. Open Graph metadata controls many social previews. It does not replace visible, meaningful content."),
("SEO starts with usability","Good headings, links, accessible content, performance, and crawlable pages matter more than keyword stuffing. The keywords meta tag is not a useful modern Google ranking tool. In this lesson, inspect your code: metadata does not appear in the visible preview.")
],'<head>\n  <title>My website</title>\n</head>\n<body><h1>Learning in public</h1></body>',"Add a meta description with a nonempty content attribute.",[["attr","meta","name","description"],["attr_nonempty","meta","content"]],"Is a meta description guaranteed to appear in search results?",["Yes","No","Only if it is uppercase"],1,"Search engines can generate a different snippet.",'<head><title>Learning in public | My studio</title><meta name="description" content="Follow my journey learning accessible web design."></head><body><h1>Learning in public</h1></body>')

H("04 / Beyond basics","html-accessibility","Keyboard & accessible names",14,"Build interfaces more people can use.",[
("Native elements first","Use a real button rather than a clickable div. Native controls provide focus and keyboard activation automatically. ARIA adds semantics but does not implement behavior."),
("Keep a logical focus order","DOM order should match reading order. Avoid positive tabindex values that create a competing order. tabindex=\"0\" includes a custom element in normal focus order; -1 supports programmatic focus without tab sequence inclusion."),
("Names and instructions","Visible labels are usually best. Icon-only buttons need an accessible name such as aria-label. Keep focus indicators visible. Use aria-describedby for supporting instructions, not as the primary name.")
],'<button>×</button>\n<p id="help">Your progress is saved after each completed lesson.</p>',"Give the icon button aria-label=\"Close panel\" and aria-describedby=\"help\".",[["attr","button","aria-label","Close panel"],["attr","button","aria-describedby","help"]],"Does role=\"button\" automatically add keyboard activation?",["Yes","No","Only in CSS Grid"],1,"ARIA changes semantics, not behavior. A native button is safer.",'<button aria-label="Close panel" aria-describedby="help">×</button><p id="help">Your progress is saved after each completed lesson.</p>')

H("04 / Beyond basics","html-disclosure","Details & disclosure",8,"Add interaction without writing JavaScript.",[
("Native disclosure","details creates an expandable region. Its first summary is the always-visible trigger. The browser handles keyboard interaction and expanded state."),
("Start open intentionally","The open boolean attribute expands details initially. Like other boolean attributes, open=\"false\" still opens it."),
("Use the right pattern","Disclosure works for supplementary content and FAQs. It is not a replacement for navigation or for content every reader must see immediately.")
],'<h1>Frequently asked questions</h1>',"Add details containing a summary and a paragraph answer.",[["tag","details"],["tag","summary"],["tag","p"]],"How do you make details initially expanded?",["Add open","Add expanded=\"true\"","Use a larger font"],0,"The open boolean attribute controls the initial expanded state.",'<h1>Frequently asked questions</h1><details><summary>Do I need JavaScript yet?</summary><p>Not for a native disclosure. HTML already has useful interactive elements.</p></details>')

H("04 / Beyond basics","html-embeds","Iframes & trust boundaries",12,"Understand what you embed.",[
("A separate document","iframe embeds another browsing context. Give it a title describing the embedded content. Loading a third-party frame may share network metadata and load tracking resources."),
("Least privilege","sandbox restricts scripts, forms, popups, and other capabilities unless individually allowed. Combining allow-scripts and allow-same-origin for same-origin untrusted content can undermine isolation."),
("Permissions and privacy","The allow attribute controls selected browser features. referrerpolicy changes referrer information. Only grant the capabilities the embedded content actually requires.")
],'<iframe srcdoc="<h1>Hello from another document</h1>"></iframe>',"Add a descriptive title and an empty sandbox attribute.",[["attr_nonempty","iframe","title"],["attr","iframe","sandbox"]],"Why should an iframe have a title?",["To make its border wider","To identify the embedded content accessibly","To enable scripts"],1,"The title helps assistive technology users understand the frame.",'<iframe title="HTML demonstration" sandbox srcdoc="<h1>Hello from another document</h1>"></iframe>')

H("05 / Production HTML","html-svg","SVG & scalable graphics",12,"Draw crisp interface graphics with markup.",[
("Vector shapes","SVG describes shapes rather than a bitmap grid. circle, rect, and path can scale without pixelation. viewBox defines an internal coordinate system."),
("Accessible or decorative","An informative inline SVG can use role=\"img\" with a title linked by aria-labelledby. Pure decoration should be hidden with aria-hidden=\"true\"."),
("Styling vectors","fill paints interiors and stroke paints outlines. currentColor inherits the CSS color property, making icons easy to theme. SVG is markup, so treat untrusted SVG content carefully.")
],'<svg viewBox="0 0 100 100" width="180" role="img" aria-labelledby="icon-title">\n  <title id="icon-title">Reactor core</title>\n</svg>',"Add a circle with cx=\"50\", cy=\"50\", r=\"35\", and a fill color.",[["attr","circle","cx","50"],["attr","circle","r","35"],["attr_nonempty","circle","fill"]],"What does viewBox define?",["A vector coordinate system","The file size in bytes","An image caption"],0,"viewBox defines the coordinate space that scales into the SVG viewport.",'<svg viewBox="0 0 100 100" width="180" role="img" aria-labelledby="icon-title"><title id="icon-title">Reactor core</title><circle cx="50" cy="50" r="35" fill="#f97316"/></svg>')

H("05 / Production HTML","html-loading","Loading scripts & styles",12,"Understand how a page gets ready.",[
("External stylesheets","link rel=\"stylesheet\" href=\"styles.css\" loads CSS, typically from head. External files can be cached and reused across pages."),
("defer and async","For classic external scripts, defer downloads during parsing and executes in document order after parsing. async executes when ready and does not preserve order. Module scripts defer by default."),
("Keep the critical path lean","Avoid loading unnecessary resources. Preload is a hint for a resource needed soon, not a default for everything. This lab does not execute scripts; the exercise teaches markup and loading semantics.")
],'<head><title>Launch</title></head><body><h1>Launch sequence</h1></body>',"Add a stylesheet link and an external classic script with defer.",[["attr","link","rel","stylesheet"],["attr","script","defer"],["attr_nonempty","script","src"]],"Which preserves order for classic external scripts while waiting for parsing?",["async","defer","autoplay"],1,"defer executes external classic scripts in document order after parsing.",'<head><title>Launch</title><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head><body><h1>Launch sequence</h1></body>')

H("05 / Production HTML","html-production","Ship a semantic page",18,"Combine structure, access, and navigation.",[
("Plan before styling","List the content, identify page landmarks, and choose a logical heading outline. A page should remain understandable with all CSS removed."),
("Audit the experience","Navigate with Tab and Shift+Tab. Check accessible names, meaningful links, unique ids, alternative text, and a skip link. Validate the document with the W3C Nu HTML checker."),
("Know the boundary","HTML is the foundation, not a server. Real form processing requires a backend, secure transport, validation, and thoughtful data handling. Now use your structural skills in the CSS track and project studio.")
],'<header><h1>My web studio</h1></header>',"Add a skip link to #main, main id=\"main\" with an article, and a footer.",[["attr","a","href","#main"],["attr","main","id","main"],["tag","article"],["tag","footer"]],"What should happen when CSS fails to load?",["Content should still be understandable","All navigation should disappear","The document should become an image"],0,"Semantic HTML preserves a useful reading experience without presentation.",'<a href="#main">Skip to content</a><header><h1>My web studio</h1></header><main id="main"><article><h2>Designing for everyone</h2><p>A meaningful structure is the best starting point.</p></article></main><footer>Built with HTML.</footer>')

C("01 / Foundations","css-first","Your first stylesheet",8,"Turn meaningful structure into visual design.",[
("Rules, selectors, declarations","A CSS rule targets elements with a selector and applies declarations. In h1 { color: coral; }, color is the property and coral is the value. End declarations with semicolons."),
("Three ways to add CSS","External stylesheets are the normal choice for a site. A style element embeds rules in HTML. Inline style attributes affect a single element but are harder to maintain and override."),
("Separate structure and presentation","Keep content in HTML and appearance in CSS. In this lab, edit the CSS tab and the preview will update automatically. Invalid declarations are usually ignored rather than crashing the entire stylesheet.")
],'<h1>Hello, CSS.</h1><p>Your ideas deserve a visual language.</p>',BASE,"Set h1 color to #f97316 and font-size to 48px.",[["css","color\\s*:\\s*#f97316"],["css","font-size\\s*:\\s*48px"]],"What selects the elements a rule applies to?",["A selector","A declaration value","A semicolon"],0,"The selector matches elements in the document.",BASE+'h1 { color: #f97316; font-size: 48px; }')

C("01 / Foundations","css-selectors","Selectors & relationships",10,"Target exactly what you intend.",[
("Basic selectors","A type selector such as p matches elements by name. .card matches a class, #hero an id, and [disabled] an attribute. Reusable classes are useful building blocks."),
("Combinators describe relationships",".card p matches any descendant paragraph. .card > p matches direct children. h2 + p matches an immediately following sibling, while h2 ~ p matches later sibling paragraphs."),
("Group and inspect","Separate selectors with commas to share rules. Use browser DevTools to see which selector matched, rather than adding increasingly specific rules blindly.")
],'<article class="card"><h1>Transmission</h1><p>A direct message.</p><div><p>A nested message.</p></div></article>',BASE,"Use .card > p to make only the direct paragraph orange.",[["css","\\.card\\s*>\\s*p\\s*\\{"],["css","color\\s*:"]],"What does .card > p select?",["All paragraphs on the page","Only direct p children of .card","Only nested cards"],1,"> is the direct-child combinator.",BASE+'.card > p { color: #ea580c; font-weight: 700; }')

C("01 / Foundations","css-cascade","Cascade, specificity & inheritance",14,"Understand why a style wins.",[
("The cascade is more than specificity","The browser considers origin and importance, cascade layers, specificity, scoping proximity where relevant, then source order. A later rule wins only when earlier priorities tie."),
("Specificity weights","Within the same origin/layer/importance, ids outweigh classes, attributes, and pseudo-classes, which outweigh type selectors. :where() contributes zero specificity. Avoid using !important as a default repair tool."),
("Inheritance is selective","Text properties such as color and font-family often inherit. Margin and border generally do not. inherit, initial, unset, and revert have distinct reset behaviors. Use DevTools computed styles to trace the winner.")
],'<h1 class="title">Follow the cascade.</h1>',BASE+'h1 { color: #475569; }\n.title { color: #0e7490; }\n',"Add a later .title rule setting color to #ea580c. Do not use !important.",[["css","\\.title\\s*\\{[^}]*color\\s*:\\s*#ea580c"],["css_not","!important"]],"Two equally specific rules in the same layer conflict. Which wins?",["The earlier one","The later one","The shorter one"],1,"Source order breaks a tie after the earlier cascade criteria.",BASE+'h1 { color: #475569; }\n.title { color: #0e7490; }\n.title { color: #ea580c; }')

C("01 / Foundations","css-box","The box model",12,"Master the geometry behind every layout.",[
("Four nested regions","Each element has content, padding, border, and margin. Padding is inside the border; margin separates the box from neighbors. Backgrounds paint through padding by default."),
("Predictable sizing","With content-box, width covers only content. With border-box, width includes padding and border. A common reset sets box-sizing: border-box on all elements and pseudo-elements."),
("Margin behavior","Adjacent vertical block margins can collapse in normal flow. Flex and grid items behave differently. If spacing surprises you, inspect box geometry in DevTools rather than inserting empty elements.")
],'<div class="card">A well-proportioned box.</div>',BASE+'.card { background: white; width: 260px; }',"Set box-sizing: border-box, padding: 24px, and a 2px solid border on .card.",[["css","box-sizing\\s*:\\s*border-box"],["css","padding\\s*:\\s*24px"],["css","border\\s*:\\s*2px\\s+solid"]],"With border-box, what does declared width include?",["Content only","Content, padding, and border","Margin too"],1,"border-box includes padding and border, but not margin.",BASE+'.card { background: white; width: 260px; box-sizing: border-box; padding: 24px; border: 2px solid #f97316; }')

C("01 / Foundations","css-units","Units, sizing & fluid values",12,"Design beyond fixed pixels.",[
("Choose units deliberately","px is a CSS pixel, not necessarily a device pixel. rem relates to root font size, em to a relevant font size, and percentages depend on the property and containing block."),
("Viewport units","vw and vh relate to viewport dimensions. Modern svh, lvh, and dvh address mobile browser UI changes. For long content, prefer min-height over a rigid height."),
("Fluid limits","min(), max(), and clamp() express responsive constraints. clamp(2rem, 6vw, 5rem) has a minimum, a preferred fluid value, and a maximum. A max-width in ch can limit reading line length.")
],'<h1>Think fluid.</h1><p>Layouts should respond to content and space.</p>',BASE,"Use clamp() for the h1 font-size and set p max-width to 60ch.",[["css","font-size\\s*:\\s*clamp\\("],["css","max-width\\s*:\\s*60ch"]],"What is the first argument to clamp()?",["The maximum","The minimum","The viewport width"],1,"clamp(minimum, preferred, maximum) bounds a responsive value.",BASE+'h1 { font-size: clamp(2rem, 8vw, 5rem); } p { max-width: 60ch; }')

C("02 / Visual language","css-color","Color & custom properties",12,"Build a reusable visual system.",[
("Modern color values","CSS supports named colors, hex, rgb(), hsl(), and modern color spaces such as oklch(). Alpha controls transparency. Do not rely on color alone to communicate status."),
("Custom properties","Define tokens such as --accent: #f97316 on :root and consume them with var(--accent). They cascade and normally inherit. var(--accent, coral) supplies a fallback when a variable is missing or invalid as a custom property."),
("Contrast is functional","Check text contrast against its actual background, including transparent layers. WCAG AA generally requires 4.5:1 for normal text and 3:1 for large text. A bright accent is not automatically readable.")
],'<button class="action">Launch mission</button>',BASE,"Define --accent on :root and use var(--accent) as the button background.",[["css","--accent\\s*:"],["css","background(?:-color)?\\s*:\\s*var\\(--accent\\)"]],"What does var(--accent) do?",["Defines a new class","Reads a custom property","Downloads a font"],1,"var() substitutes a custom property’s value.",BASE+':root { --accent: #c2410c; } .action { background: var(--accent); color: white; padding: 12px 20px; border: 0; }')

C("02 / Visual language","css-type","Typography & rhythm",12,"Make interfaces feel designed.",[
("Hierarchy through typography","Use a limited type scale to distinguish headings, body, and metadata. Font weight, line height, and whitespace can establish hierarchy without constantly changing fonts."),
("Readable body text","A unitless line-height around 1.5–1.7 works for many body fonts. Limit line length, avoid overly small text, and test at zoom. Large headings often need tighter line heights."),
("Loading fonts","Provide a fallback font stack. Self-hosted WOFF2 can reduce third-party dependencies. font-display: swap shows fallback text while a web font loads, but plan for possible layout shift.")
],'<article><h1>Good type speaks.</h1><p>Readable interfaces respect the reader. A consistent rhythm makes complex content feel clear, calm, and considered.</p></article>',BASE,"Set p font-size to 18px, unitless line-height to 1.7, and max-width to 60ch.",[["css","font-size\\s*:\\s*18px"],["css","line-height\\s*:\\s*1\\.7"],["css","max-width\\s*:\\s*60ch"]],"Why use a unitless line-height?",["It scales naturally with inherited font sizes","It disables wrapping","It sets the font weight"],0,"A unitless multiplier scales with each element’s font size.",BASE+'p { font-size: 18px; line-height: 1.7; max-width: 60ch; } h1 { font-size: 42px; letter-spacing: -0.04em; }')

C("02 / Visual language","css-surfaces","Backgrounds, borders & shadows",12,"Give flat elements depth without visual noise.",[
("Layered backgrounds","Multiple backgrounds are comma-separated, with the first on top. Gradients are generated images. background-size, position, and repeat determine how image layers fit."),
("Borders and corners","border-radius rounds corners; it does not always clip children unless overflow is controlled. Use subtle borders to separate nearby surfaces before adding large shadows."),
("Shadows communicate elevation","box-shadow can represent distance and depth. text-shadow affects glyphs. Keep effects restrained enough that hierarchy and readability still dominate.")
],'<article class="card"><h1>Signal detected.</h1><p>A little depth goes a long way.</p></article>',BASE+'.card { padding: 24px; }',"Add a linear-gradient background, border-radius, and box-shadow to .card.",[["css","linear-gradient\\("],["css","border-radius\\s*:"],["css","box-shadow\\s*:"]],"Which background layer is painted on top?",["The first listed","The last listed","The largest"],0,"CSS paints the first background layer closest to the viewer.",BASE+'.card { padding: 24px; color: white; background: linear-gradient(135deg, #164e63, #0f172a); border-radius: 20px; box-shadow: 0 12px 30px #0f172a33; }')

C("02 / Visual language","css-display","Display & normal flow",10,"Know the default layout before replacing it.",[
("Block and inline flow","Block boxes generally stack in the block direction; inline content flows within lines. Writing mode affects these axes. A span is inline by default; a div is block by default."),
("Choose display based on layout","inline-block creates an atomic inline box that can accept dimensions. flex and grid establish new layout contexts. display: none removes an element from layout and generally the accessibility tree."),
("Visibility and overflow","visibility: hidden keeps layout space while hiding the element. opacity: 0 makes it transparent but can leave it interactive. Handle focus and pointer behavior deliberately.")
],'<a class="badge" href="#one">HTML</a> <a class="badge" href="#two">CSS</a>',BASE,"Set .badge to inline-block and add padding and a background.",[["css","display\\s*:\\s*inline-block"],["css","padding\\s*:"],["css","background"]],"Which keeps layout space while hiding an element?",["display: none","visibility: hidden","display: contents"],1,"visibility: hidden preserves the element’s box.",BASE+'.badge { display: inline-block; padding: 8px 16px; background: #e0f2fe; border-radius: 8px; color: #075985; }')

C("03 / Layout systems","css-flex","Flexbox fundamentals",14,"Arrange interfaces along one primary axis.",[
("Container and items","display: flex turns direct children into flex items. flex-direction defines the main axis. justify-content aligns along the main axis; align-items aligns along the cross axis."),
("Space and sizing","gap creates space between items. flex-grow distributes available space; flex-shrink handles negative free space; flex-basis gives the starting size. The shorthand flex: 1 commonly creates flexible equal-share items."),
("Common overflow fix","Flex items often have an automatic minimum size. min-width: 0 on a child lets it shrink below its content’s intrinsic width. Do not use visual order to create a confusing keyboard order.")
],'<nav class="nav"><strong>AXIOM</strong><a href="#learn">Learn</a><a href="#build">Build</a></nav>',BASE,"Make .nav a flex container with align-items: center, justify-content: space-between, and gap: 16px.",[["css","display\\s*:\\s*flex"],["css","align-items\\s*:\\s*center"],["css","justify-content\\s*:\\s*space-between"]],"In a row flex container, justify-content aligns along which axis?",["The horizontal main axis","Always the vertical axis","The z axis"],0,"With default horizontal writing mode and flex-direction: row, the main axis is horizontal.",BASE+'.nav { display: flex; align-items: center; justify-content: space-between; gap: 16px; background: white; padding: 20px; }')

C("03 / Layout systems","css-flex-wrap","Flexible components & wrapping",12,"Make components survive real content.",[
("Wrap instead of squeeze","flex-wrap: wrap lets items form multiple lines. Each line distributes its own space; flexbox does not align columns across rows like Grid."),
("A useful card pattern","flex: 1 1 200px lets a card grow, shrink, and start at a 200px basis. Test long labels and narrow viewports. A flex basis is not always the final width."),
("Centering and alignment","align-self overrides cross-axis alignment for one item. Auto margins can absorb available main-axis space, useful for pushing a navigation action to the far edge.")
],'<div class="cards"><article>Structure</article><article>Style</article><article>Ship</article></div>',BASE+'.cards { display: flex; gap: 16px; } article { padding: 24px; background: white; }',"Allow wrapping and give each article flex: 1 1 180px.",[["css","flex-wrap\\s*:\\s*wrap"],["css","flex\\s*:\\s*1\\s+1\\s+180px"]],"Does each wrapped flex line distribute its space independently?",["Yes","No","Only with a fixed height"],0,"Each flex line lays out independently; use Grid for aligned rows and columns.",BASE+'.cards { display: flex; gap: 16px; flex-wrap: wrap; } article { flex: 1 1 180px; padding: 24px; background: white; }')

C("03 / Layout systems","css-grid","CSS Grid fundamentals",14,"Think in rows and columns.",[
("A two-dimensional system","display: grid lays out direct children in tracks. Define columns with grid-template-columns and rows with grid-template-rows. gap controls gutters."),
("Flexible tracks","fr units distribute remaining space. repeat(3, 1fr) creates three equal fractions, but intrinsic minimum sizing can still cause overflow. minmax(0, 1fr) is useful for tracks that must shrink."),
("Placement","grid-column: span 2 spans two columns. Named areas can make page layouts explicit. Keep source order meaningful regardless of visual placement.")
],'<div class="grid"><article>01 / HTML</article><article>02 / CSS</article><article>03 / Build</article></div>',BASE+'article { background: white; padding: 20px; }',"Use display: grid, grid-template-columns: repeat(3, 1fr), and gap: 16px.",[["css","display\\s*:\\s*grid"],["css","grid-template-columns\\s*:\\s*repeat\\(3,\\s*1fr\\)"],["css","gap\\s*:\\s*16px"]],"What is Grid especially suited to?",["Two-dimensional layouts","Only text styling","Only animations"],0,"Grid coordinates rows and columns.",BASE+'.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; } article { background: white; padding: 20px; }')

C("03 / Layout systems","css-grid-responsive","Responsive grids & subgrid",14,"Build layouts that adapt without endless breakpoints.",[
("Auto-fitting tracks","repeat(auto-fit, minmax(180px, 1fr)) creates as many columns as fit. auto-fit collapses empty tracks; auto-fill preserves them."),
("Avoid tiny-screen overflow","A hard minimum can overflow an extremely narrow container. minmax(min(100%, 180px), 1fr) is a robust alternative when supported in your target browsers."),
("Subgrid","grid-template-columns: subgrid lets a nested grid align with parent columns it spans. It is useful for consistent card content alignment; check your support targets before depending on it.")
],'<div class="grid"><article>Learn</article><article>Practice</article><article>Build</article><article>Publish</article></div>',BASE+'.grid { display: grid; gap: 16px; } article { padding: 24px; background: white; }',"Use repeat(auto-fit, minmax(180px, 1fr)) for grid-template-columns.",[["css","repeat\\(\\s*auto-fit"],["css","minmax\\(\\s*180px\\s*,\\s*1fr"]],"What does auto-fit do with empty tracks?",["Collapses them","Adds more","Turns them into flex items"],0,"auto-fit collapses empty repeated tracks so filled tracks can grow.",BASE+'.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); } article { padding: 24px; background: white; }')

C("03 / Layout systems","css-position","Positioning & stacking",14,"Place elements without fighting the layout.",[
("Positioning modes","relative preserves the original space and can establish a containing block. absolute leaves normal flow and positions relative to a containing block, often the nearest positioned ancestor."),
("Sticky versus fixed","fixed usually anchors to the viewport, though some properties can establish a different containing block. sticky stays in flow, then sticks within its scrolling context when a threshold such as top is reached."),
("Stacking contexts","z-index is not globally comparable across every element. Transforms, opacity below 1, and other properties can create stacking contexts. A huge z-index cannot escape an ancestor’s stacking context.")
],'<article class="card"><span class="badge">NEW</span><h1>Position with purpose.</h1></article>',BASE+'.card { padding: 40px 24px; background: white; }',"Set .card position: relative and .badge position: absolute with top: 12px and right: 12px.",[["css","position\\s*:\\s*relative"],["css","position\\s*:\\s*absolute"],["css","top\\s*:\\s*12px"],["css","right\\s*:\\s*12px"]],"Does absolute positioning reserve its original flow space?",["Yes","No","Only in a table"],1,"Absolutely positioned boxes leave normal flow.",BASE+'.card { position: relative; padding: 40px 24px; background: white; } .badge { position: absolute; top: 12px; right: 12px; color: #c2410c; }')

C("04 / Responsive design","css-media","Media queries & mobile first",14,"Adapt to available space, not device names.",[
("Start small","Write the narrow layout first, then enhance at min-width breakpoints. Choose breakpoints when the content needs them, not because a particular phone exists."),
("A query is a condition","@media (min-width: 700px) applies only when the viewport is wide enough. Media features also include hover, pointer, color scheme, print, and reduced motion."),
("Test real conditions","Resize gradually, zoom text, and test keyboard access. The viewport meta tag belongs in HTML. Avoid disabling user zoom.")
],'<div class="layout"><article>Content</article><aside>Related lessons</aside></div>',BASE+'.layout { display: grid; gap: 16px; } article, aside { background: white; padding: 24px; }',"At min-width: 700px, give .layout two columns using 2fr 1fr.",[["css","@media\\s*\\(min-width\\s*:\\s*700px\\)"],["css","grid-template-columns\\s*:\\s*2fr\\s+1fr"]],"What should determine a breakpoint?",["Where content needs a layout change","A random popular phone width","The number of CSS files"],0,"Content-driven breakpoints keep layouts resilient.",BASE+'.layout { display: grid; gap: 16px; } article, aside { background: white; padding: 24px; } @media (min-width: 700px) { .layout { grid-template-columns: 2fr 1fr; } }')

C("04 / Responsive design","css-container","Container queries",14,"Let a component respond to its own space.",[
("Viewport is not always enough","A card may live in a sidebar or a full-width area on the same viewport. Container queries style descendants according to an eligible ancestor’s size."),
("Establish containment","container-type: inline-size enables inline-size queries. A container-name can target a specific container. Query styles apply to descendants, not the container’s own size based on itself."),
("Progressive enhancement","Provide a useful default layout, then enhance with @container. This lets components work in a variety of page contexts without knowing the entire page layout.")
],'<section class="wrapper"><article class="card"><h1>One component.</h1><p>Many contexts.</p></article></section>',BASE+'.card { background: white; padding: 24px; }',"Set .wrapper container-type: inline-size. At @container (min-width: 400px), make .card display: flex.",[["css","container-type\\s*:\\s*inline-size"],["css","@container\\s*\\(min-width\\s*:\\s*400px\\)"],["css","display\\s*:\\s*flex"]],"A size container query responds to what?",["An eligible ancestor container","Only screen resolution","The network speed"],0,"A container query evaluates an eligible container’s dimensions.",BASE+'.wrapper { container-type: inline-size; } .card { background: white; padding: 24px; } @container (min-width: 400px) { .card { display: flex; align-items: center; gap: 24px; } }')

C("04 / Responsive design","css-images","Object fit & aspect ratio",10,"Keep visual media intentional.",[
("Reserve a shape","aspect-ratio provides a preferred width-to-height ratio. It helps reserve space and keep media consistent as width changes."),
("Fit versus fill","object-fit: cover fills an image/video box and may crop; contain preserves all content and may leave empty space. object-position controls which part stays visible."),
("Background or content?","Use img for meaningful content because it supports alt text and resource selection. Background images are better for decoration; they have no alt attribute.")
],'<img class="cover" src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600" alt="Sunlight in a forest">',BASE,"Set .cover width: 100%, aspect-ratio: 16 / 9, and object-fit: cover.",[["css","aspect-ratio\\s*:\\s*16\\s*/\\s*9"],["css","object-fit\\s*:\\s*cover"]],"Which value may crop an image to fill its box?",["contain","cover","scale-down"],1,"cover fills both dimensions while preserving the intrinsic ratio.",BASE+'.cover { width: 100%; aspect-ratio: 16 / 9; object-fit: cover; border-radius: 16px; }')

C("05 / Interaction & motion","css-states","Pseudo-classes & focus",12,"Design every interaction state.",[
("State selectors",":hover targets pointer hover; :active matches activation; :focus-visible generally indicates keyboard-style focus. Touch users may not have hover, so never hide essential functionality behind it."),
("Structural selectors",":first-child, :nth-child(), :not(), :is(), and :has() express structural conditions. :has() can select based on a relative selector, but keep complex rules understandable."),
("Accessible focus","Do not remove outlines without a strong replacement. Pair focus styles with hover styling. Disabled states should remain legible and must be functionally disabled, not merely grey.")
],'<button class="action">Focus me with Tab</button>',BASE+'.action { padding: 14px 24px; background: #0f172a; color: white; border: 0; }',"Add .action:hover with a different background and .action:focus-visible with a 3px solid outline.",[["css",":hover"],["css",":focus-visible"],["css","outline\\s*:\\s*3px\\s+solid"]],"Why keep a visible focus indicator?",["To show keyboard users their current target","To slow down the page","Only to decorate screenshots"],0,"Visible focus makes keyboard navigation understandable.",BASE+'.action { padding: 14px 24px; background: #0f172a; color: white; border: 0; } .action:hover { background: #334155; } .action:focus-visible { outline: 3px solid #f97316; outline-offset: 4px; }')

C("05 / Interaction & motion","css-pseudo","Pseudo-elements & decorative detail",10,"Add visual accents without extra markup.",[
("Generated boxes","::before and ::after create generated boxes associated with an element. They generally need content, even content: \"\", to render."),
("Use them for decoration","Underlines, badges, and background shapes are good uses. Do not put essential instructions only in generated content because its accessibility and copying behavior can vary."),
("Other pseudo-elements","::selection styles selected text. ::marker styles list markers. Pseudo-elements are not the same as pseudo-classes: one creates/selects a part, the other matches a state or relationship.")
],'<h1 class="title">Designed with detail.</h1>',BASE,"Create .title::after with content: \"\", display: block, height: 4px, and a background color.",[["css","::after"],["css","content\\s*:"],["css","height\\s*:\\s*4px"]],"Which is a pseudo-element?",[":hover","::after",":focus"],1,"Double-colon ::after denotes a generated pseudo-element.",BASE+'.title::after { content: ""; display: block; width: 64px; height: 4px; background: #ea580c; margin-top: 16px; }')

C("05 / Interaction & motion","css-transitions","Transforms & transitions",12,"Make changes feel deliberate.",[
("Transforms move the visual box","translate, rotate, and scale transform rendering without rearranging normal flow. Use transform-origin to control the pivot."),
("Transitions interpolate changes","A transition animates between property values when a state changes. Declare specific properties rather than transition: all. Duration, delay, and easing shape the experience."),
("Performance and comfort","Transform and opacity are often cheaper to animate than layout properties such as width or top, but performance still depends on the element and browser. Avoid large motion and support reduced motion.")
],'<button class="action">Hover to lift</button>',BASE+'.action { padding: 20px; border: 0; background: #0f172a; color: white; }',"Add a transform transition and translateY(-4px) on hover.",[["css","transition\\s*:\\s*transform"],["css","translateY\\(-4px\\)"]],"Does transform normally rearrange neighboring elements?",["Yes","No","Only at 60fps"],1,"Transforms affect rendering without changing normal-flow layout.",BASE+'.action { padding: 20px; border: 0; background: #0f172a; color: white; transition: transform 180ms ease; } .action:hover { transform: translateY(-4px); }')

C("05 / Interaction & motion","css-animation","Keyframes & cinematic motion",14,"Build a reactor-style animation.",[
("Define a timeline","@keyframes names a sequence of styles. Use from/to or percentage stops. animation applies the name, duration, timing function, and iteration count."),
("Loops and state","linear produces a steady spin; ease creates acceleration/deceleration. animation-fill-mode controls how styles apply outside the active animation interval. Infinite animation should be purposeful, not distracting."),
("Keep control with the reader","Provide a pause control for persistent decorative motion and respect prefers-reduced-motion. Avoid flashing effects. The next lesson adds the accessibility layer.")
],'<div class="ring" aria-label="Decorative reactor ring"></div>',BASE+'.ring { width: 120px; height: 120px; border: 5px solid #cbd5e1; border-top-color: #f97316; border-radius: 50%; }',"Define @keyframes spin ending at rotate(360deg) and apply animation: spin 4s linear infinite to .ring.",[["css","@keyframes\\s+spin"],["css","rotate\\(360deg\\)"],["css","animation\\s*:\\s*spin\\s+4s\\s+linear\\s+infinite"]],"What makes a rotation move at constant speed?",["linear easing","ease-in easing","A larger border"],0,"linear progresses at a constant rate.",BASE+'.ring { width: 120px; height: 120px; border: 5px solid #cbd5e1; border-top-color: #f97316; border-radius: 50%; animation: spin 4s linear infinite; } @keyframes spin { to { transform: rotate(360deg); } }')

C("05 / Interaction & motion","css-reduced-motion","Reduced motion & user preferences",10,"Make impressive interfaces comfortable.",[
("Respect motion sensitivity","@media (prefers-reduced-motion: reduce) detects a user preference for less non-essential movement. It is not a preference for broken interactions."),
("Replace rather than just accelerate","Remove large-scale transforms and continuous loops where possible. Keep essential state changes clear without relying on animation completion events."),
("More preferences","prefers-color-scheme can inform themes, but user overrides are helpful. Test forced-colors mode too; system color choices can change borders and backgrounds.")
],'<div class="ring"></div>',BASE+'.ring { width: 100px; height: 100px; border: 5px solid #cbd5e1; border-top-color: #ea580c; border-radius: 50%; animation: spin 3s linear infinite; } @keyframes spin { to { transform: rotate(360deg); } }',"Add a prefers-reduced-motion: reduce query that sets .ring animation: none.",[["css","prefers-reduced-motion\\s*:\\s*reduce"],["css","animation\\s*:\\s*none"]],"Should reduced motion remove essential functionality?",["Yes","No","Only on mobile"],1,"Reduce non-essential motion while preserving a clear, usable interface.",BASE+'.ring { width: 100px; height: 100px; border: 5px solid #cbd5e1; border-top-color: #ea580c; border-radius: 50%; animation: spin 3s linear infinite; } @keyframes spin { to { transform: rotate(360deg); } } @media (prefers-reduced-motion: reduce) { .ring { animation: none; } }')

C("06 / Production CSS","css-layers","Layers & maintainable architecture",14,"Keep styles predictable as projects grow.",[
("Organize intent","Separate resets, tokens, base elements, reusable components, and utilities. A naming convention such as .card__title makes ownership clear; consistency matters more than one fashionable convention."),
("Cascade layers","@layer reset, base, components, utilities establishes order for normal declarations. Later layers outrank earlier layers before specificity; unlayered normal author styles outrank layered normal author styles."),
("Important reverses layer priority","For !important declarations, layer precedence reverses. Prefer a deliberate layer strategy over a contest of selector specificity and !important overrides.")
],'<button class="button">A maintainable component</button>',BASE,"Create an @layer components block containing a .button rule with padding and background.",[["css","@layer\\s+components"],["css","\\.button\\s*\\{"],["css","padding\\s*:"]],"For normal declarations, which declared layer has higher precedence?",["An earlier layer","A later layer","Whichever has the longer name"],1,"Later layers win for normal declarations, before specificity is compared.",BASE+'@layer components { .button { padding: 14px 24px; background: #0f172a; color: white; border: 0; border-radius: 8px; } }')

C("06 / Production CSS","css-logical","Logical properties & international layouts",10,"Design for more than left-to-right text.",[
("Think inline and block","margin-inline and padding-block describe relationships to writing direction. width maps to inline-size in common horizontal writing modes; height maps to block-size."),
("Direction-aware interfaces","margin-inline-start adapts between left-to-right and right-to-left layouts. Logical properties can remove duplicated RTL overrides, but inspect icons and reading order too."),
("Content expansion","Translated text may be longer. Avoid fixed-height text boxes and rigid button widths. Test with long content and larger user font settings.")
],'<article class="card" dir="rtl"><h1>مرحبا بالعالم</h1><p>A layout that respects direction.</p></article>',BASE+'.card { background: white; }',"Use padding-inline: 24px, padding-block: 16px, and border-inline-start on .card.",[["css","padding-inline\\s*:\\s*24px"],["css","padding-block\\s*:\\s*16px"],["css","border-inline-start\\s*:"]],"Which adapts to writing direction?",["margin-left","margin-inline-start","left"],1,"Logical start/end properties adapt to writing direction.",BASE+'.card { background: white; padding-inline: 24px; padding-block: 16px; border-inline-start: 4px solid #ea580c; }')

C("06 / Production CSS","css-debug","Debugging, support & performance",14,"Fix causes, not symptoms.",[
("Use the browser’s instruments","Inspect matched rules, computed styles, box model, Flexbox and Grid overlays, and accessibility information. Disable a declaration to test a hypothesis before rewriting the component."),
("Feature detection","@supports tests whether a declaration is understood. Start with a workable fallback and enhance when supported. Syntax support does not guarantee every usage is bug-free."),
("Measure performance","Use Lighthouse and the browser Performance panel as diagnostics, not as the only quality measure. Oversized images, web fonts, costly effects, and large layout changes can matter more than selector micro-optimizations.")
],'<div class="layout"><article>A progressive enhancement.</article><article>A resilient fallback.</article></div>',BASE+'.layout { display: block; } article { padding: 20px; margin-bottom: 16px; background: white; }',"Add @supports (display: grid) and use display: grid with a gap on .layout inside it.",[["css","@supports\\s*\\(display\\s*:\\s*grid\\)"],["css","gap\\s*:"]],"What does @supports check?",["Whether a CSS feature is understood","Whether the user is online","Whether a font looks good"],0,"@supports provides CSS feature-query conditions.",BASE+'.layout { display: block; } article { padding: 20px; margin-bottom: 16px; background: white; } @supports (display: grid) { .layout { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } }')

C("06 / Production CSS","css-ship","Ship a responsive design system",20,"Combine your skills into a production-minded interface.",[
("Build from tokens","Define a spacing scale, readable typography, colors with checked contrast, and reusable component styles. Let tokens carry decisions consistently across a site."),
("Verify the whole experience","Test from narrow mobile to wide desktop, keyboard-only navigation, 200% zoom, reduced motion, long content, loading failures, and real touch interaction. Check more than one browser."),
("Publish deliberately","Use the project studio to build a portfolio, editorial page, and dashboard. HTML and CSS can publish as static files. Accounts, protected data, and persistence require a backend; Java and JavaScript are separate future learning choices.")
],'<main><h1>Ready for launch.</h1><div class="grid"><article><h2>Structure</h2><p>Semantic and accessible.</p></article><article><h2>Style</h2><p>Responsive and resilient.</p></article></div></main>',BASE,"Create a responsive auto-fit grid, define --accent, and give articles a border-radius.",[["css","--accent\\s*:"],["css","auto-fit"],["css","border-radius\\s*:"]],"Which belongs in a final QA pass?",["Only a desktop screenshot","Keyboard, mobile, zoom, motion, and browser checks","Removing every focus outline"],1,"A production-minded interface works across inputs, preferences, sizes, and browsers.",BASE+':root { --accent: #c2410c; } h1 { color: var(--accent); } .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; } article { padding: 24px; background: white; border-radius: 16px; }')

projects=[
dict(id="portfolio",title="Your personal orbit",type="Portfolio",level="Beginner",time="45–60 min",description="Design a personal portfolio that feels unmistakably yours. Introduce yourself, showcase three projects, and make it easy to get in touch.",tags=["Semantic HTML","Flexbox","Responsive"],checklist=["A header, main, and footer","A clear h1 and a short introduction","Three project cards with descriptive links","Responsive layout with no horizontal overflow","Visible keyboard focus and readable contrast"],html='<header><a href="#">YOUR NAME / STUDIO</a><nav><a href="#work">Work</a> <a href="#contact">Contact</a></nav></header>\n<main><section class="hero"><p>DESIGNER & DEVELOPER</p><h1>I build things<br>for the web.</h1><p>Thoughtful interfaces. Meaningful experiences.</p></section>\n<section id="work"><h2>Selected work</h2><div class="projects"><article><h3>Project one</h3><p>Your next great idea goes here.</p><a href="#contact">Let’s talk →</a></article></div></section>\n<section id="contact"><h2>Start a conversation.</h2><a href="mailto:hello@example.com">hello@example.com</a></section></main>\n<footer>Made with intention.</footer>',css='body { margin: 0; background: #f5f1ea; color: #232323; font-family: system-ui; line-height: 1.6; padding: 5%; }\nheader { display: flex; justify-content: space-between; gap: 24px; flex-wrap: wrap; }\na { color: inherit; }\n.hero { padding: 70px 0; }\nh1 { font-size: clamp(42px, 9vw, 90px); letter-spacing: -.06em; line-height: 1; }\n.projects { display: grid; gap: 20px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }\narticle { background: #e5dfd5; padding: 24px; border-radius: 8px; }\n#contact { padding: 60px 0; }\n:focus-visible { outline: 3px solid #b45309; outline-offset: 4px; }'),
dict(id="editorial",title="The next chapter",type="Editorial",level="Intermediate",time="60–90 min",description="Build an editorial magazine page with strong typography, a featured story, and a responsive story grid.",tags=["Typography","CSS Grid","Images"],checklist=["A semantic article and logical heading hierarchy","A featured figure with alternative text and caption","A three-story grid that collapses on mobile","A comfortable body line length and line height","A responsive image with reserved dimensions"],html='<header><strong>FORM / JOURNAL</strong></header><main><article><p>ISSUE 001 — DESIGN</p><h1>The quiet power<br>of good design.</h1><p class="intro">Less noise. More meaning. An exploration of interfaces that put people first.</p><hr><h2>Space to think</h2><p>Begin your story here. Use structure and whitespace to guide the reader.</p></article></main>',css='body { background: #f3f0e9; color: #232323; font-family: Georgia, serif; padding: 6%; line-height: 1.7; }\nheader { border-bottom: 2px solid; padding-bottom: 20px; font-family: system-ui; }\nh1 { font-size: clamp(40px, 7vw, 80px); line-height: 1.05; font-weight: 400; }\np { max-width: 65ch; }\n.intro { font-size: 22px; }\nhr { margin: 40px 0; border: 0; border-top: 1px solid #ccc; }'),
dict(id="reactor",title="Mission control",type="HUD dashboard",level="Advanced",time="90–120 min",description="Create your own futuristic command center with a CSS reactor, responsive telemetry panels, and accessible motion.",tags=["Keyframes","Grid","Custom properties"],checklist=["A responsive dashboard grid","Three reusable metric components","A reactor animated with transform","A prefers-reduced-motion fallback","Readable contrast, focus indicators, and semantic landmarks"],html='<header><strong>NEXUS / CONTROL</strong><span> SYSTEM ONLINE</span></header><main><p>WELCOME, OPERATOR</p><h1>All systems. Aligned.</h1><div class="reactor" aria-hidden="true"></div><section class="metrics" aria-label="System telemetry"><article><p>STRUCTURE</p><h2>HTML</h2></article><article><p>VISUAL ENGINE</p><h2>CSS</h2></article></section></main>',css=':root { --accent: #67e8f9; }\nbody { margin: 0; background: #081018; color: #e6f5fa; font-family: system-ui; padding: 5%; }\nheader { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 20px; border-bottom: 1px solid #234050; padding-bottom: 20px; }\nheader span, main > p { color: var(--accent); font: 12px monospace; letter-spacing: 2px; }\nh1 { font-size: clamp(32px, 6vw, 60px); letter-spacing: -.04em; }\n.reactor { width: 140px; height: 140px; margin: 40px auto; border: 2px solid #234050; border-top-color: var(--accent); border-radius: 50%; box-shadow: 0 0 35px #67e8f920; animation: orbit 6s linear infinite; }\n.metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; }\narticle { border: 1px solid #234050; padding: 20px; }\narticle p { font: 11px monospace; color: var(--accent); }\n@keyframes orbit { to { transform: rotate(360deg); } }\n@media (prefers-reduced-motion: reduce) { .reactor { animation: none; } }')
]
for i,l in enumerate(LESSONS):
    l['number']=i+1
    l['xp']=100 if l['minutes']<14 else 150
(Path(__file__).resolve().parent / 'data' / 'curriculum.json').write_text(json.dumps(dict(lessons=LESSONS,projects=projects),ensure_ascii=False))
print(f"Wrote {len(LESSONS)} lessons: {sum(l['track']=='html' for l in LESSONS)} HTML / {sum(l['track']=='css' for l in LESSONS)} CSS, {len(projects)} projects")